/*
	PACKAGE
	- 비슷한 기능을 제공하는 프로시저나 함수들을 모아 둔 객체
	- 패키지는 선언부, 구형부로 나뉨
	- 선언부 (PACKAGE) : 프로시저, 함수, 변수, 상수, 커서 등등을 선언 (LIKE INTERFACE)
	- 구현부 (PACKAGE BODY) : 구현 코드들을 정의
	- PUBLIC ITEM : 선언부에 사용하고 패키지 외부에서 사용이 가능
	- PRIVATE ITEM : 구현부에 선언하고 패키지 내부에서만 사용
*/

-- PACKAGE  생성
CREATE OR REPLACE PACKAGE PKG_EMP 
IS 
	-- 상수 선언 *PUBLIC ITEM*
	C_PUBLIC CONSTANT  VARCHAR2(100) := 'PUBLIC ITEM';

	-- 프로시저 선언
	PROCEDURE PROC_TEST(P_IN IN NUMBER);
	PROCEDURE PROC_TEST2(
		P_IN IN NUMBER,
		P_OUT OUT NUMBER,
		P_INOUT IN OUT NUMBER
	);
	PROCEDURE PROC_TEST3(
		P_NUM1 IN NUMBER,
		P_NUM2 OUT NUMBER,
		P_SUM IN OUT NUMBER
	);
	
	-- 함수 선언
	 FUNCTION FUNC_GETDEPTID (
		P_EMP_ID IN EMPLOYEES.EMPLOYEE_ID%TYPE
	)
	RETURN NUMBER;
	FUNCTION FUNC_EMP_FULLNAME(
		P_EMP_ID EMPLOYEES.EMPLOYEE_ID%TYPE
	)
	RETURN VARCHAR2;
END;

--PACKAGE BODY 생성
CREATE OR REPLACE PACKAGE BODY PKG_EMP 
IS
	-- 변수 선언 (PRIVATE ITEM)
	V_PRIVATE VARCHAR2(100) := 'PRIVATE ITEM';

	-- 프로시저 구현
	PROCEDURE PROC_TEST(P_IN IN NUMBER)
	IS
		-- 변수, 상수, 커서, 타입 ...선언부
	BEGIN
		PL('IN파라미터 P_IN의 값 : ' || P_IN);
	END;
	
	PROCEDURE PROC_TEST2(
		P_IN IN NUMBER,
		P_OUT OUT NUMBER,
		P_INOUT IN OUT NUMBER
	)
	IS
	BEGIN
		PL('P_IN 변수가 전달 받은 값 : '|| P_IN);
		PL('P_INOUT 변수가 전달 받은 값 : '|| P_INOUT);
		P_OUT := 40;
		P_INOUT := 50;
	END;
	
	PROCEDURE PROC_TEST3(
		P_NUM1 IN NUMBER,
		P_NUM2 IN NUMBER,
		P_SUM IN OUT NUMBER
	)
	IS
	BEGIN
		P_SUM := P_NUM1 + P_NUM2;
	END;
		
	-- 함수 구현
	FUNCTION FUNC_GETDEPTID (
		P_EMP_ID IN EMPLOYEES.EMPLOYEE_ID%TYPE
	)
	RETURN NUMBER
	IS
		V_DEPT_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
	BEGIN 
		SELECT DEPARTMENT_ID INTO V_DEPT_ID
		FROM EMPLOYEES
		WHERE EMPLOYEE_ID = P_EMP_ID;
		RETURN V_DEPT_ID;
	END;
	
	FUNCTION FUNC_EMP_FULLNAME(
		P_EMP_ID EMPLOYEES.EMPLOYEE_ID%TYPE
	)
	RETURN VARCHAR2
	IS
		V_FULLNAME VARCHAR2(46);
	BEGIN
		SELECT FIRST_NAME||' '||LAST_NAME INTO V_FULLNAME
		FROM EMPLOYEES
		WHERE EMPLOYEE_ID = P_EMP_ID;
		RETURN V_FULLNAME;
	END;

END;

-- 패키지 사용

-- 패키지 내의 변수 호출
BEGIN
	-- 패키지 선언부에 선언한 상수는 패키지 외부에서 접근 가능
	PL(PKG_EMP.C_PUBLIC);
	-- 패키지 구현부에 선언한 변수는 패키지 외부에서 접근 불가
	--	PL(PKG_EMP.V_PRIVATE);
END;

-- 패키지 내의 프로시저 호출
DECLARE
	V_SUM NUMBER;
BEGIN
	PKG_EMP.PROC_TEST3(10, 20, V_SUM);
	PL(V_SUM);
END;

-- 패키지 내의 함수 호출
SELECT PKG_EMP.FUNC_EMP_FULLNAME(100) FROM DUAL;








