-- DDL : 데이터 정의어
-- 데이터베이스 객체에 대한 작업
-- CREATE, ALTER, DROP, RENAME, TRUNCATE ...

-- CREATE : 생성
CREATE TABLE TABLE1 (
	T1ID NUMBER PRIMARY KEY,
	CONTENT NVARCHAR2(2000)
);
CREATE SEQUENCE SEQ_TABLE1;

-- ALTER : 수정
ALTER TABLE NEWTABLE1 ADD (ETC NVARCHAR2(200)); -- 컬럼 추가
ALTER TABLE NEWTABLE1 RENAME COLUMN ETC TO NEWETC; -- 컬럼명 변경
ALTER TABLE TABLE1 MODIFY (ETC NVARCHAR2(500)); -- 컬럼 수정
ALTER TABLE TABLE1 DROP COLUMN ETC; -- 컬럼 제거
ALTER TABLE TABLE1 RENAME TO NEWTABLE1; -- 테이블명 변경

-- 테이블에 데이터 등록
INSERT INTO NEWTABLE1 VALUES(SEQ_TABLE1.NEXTVAL, 'CONTENT1', 'ETC1');
INSERT INTO NEWTABLE1 VALUES(SEQ_TABLE1.NEXTVAL, 'CONTENT2', 'ETC2');
COMMIT;
SELECT * FROM NEWTABLE1;

-- TRUNCATE : 데이터 삭제 후 즉시 COMMIT (ROLLBACK X)
TRUNCATE TABLE NEWTABLE1;
SELECT * FROM NEWTABLE1;
ROLLBACK;
SELECT * FROM NEWTABLE1;

-- DROP : 객체 제거 (ROLLBACK X)
DROP TABLE NEWTABLE1;
DROP SEQUENCE SEQ_TABLE1;