-- 1) 사원번호 100번의 풀네임, 이메일, 급여를 RECORD에 저장 후 출력
DECLARE
TYPE REC_EMP IS RECORD
(
	FULLNAME VARCHAR2(46),
	EMAIL EMPLOYEES.EMAIL%TYPE,
	SALARY EMPLOYEES.SALARY%TYPE
);
V_REC_EMP REC_EMP; -- REC_EMP타입으로 만들어진 변수 선언
BEGIN
	SELECT FIRST_NAME||' '||LAST_NAME, EMAIL, SALARY
	INTO V_REC_EMP -- 3개의 값을 한 번에 담음, 해당 타입의 변수들만 모아놨으니까
	FROM EMPLOYEES
	WHERE EMPLOYEE_ID=100;
	PL(V_REC_EMP.FULLNAME);
	PL(V_REC_EMP.EMAIL);
	PL(V_REC_EMP.SALARY);
END;


-- 2) 60번 부서에 근무하는 사원들의 급여를 중첩테이블에 저장하고 평균을 구해 출력
DECLARE
	TYPE NT_SALARY IS TABLE OF NUMBER;
	V_NT_SALARY NT_SALARY := NT_SALARY();
	TOTAL NUMBER := 0; --합계
BEGIN
	FOR EMPSAL IN (SELECT SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID=60)
	LOOP
		V_NT_SALARY.EXTEND; -- 공간확장
		V_NT_SALARY(V_NT_SALARY.COUNT) := EMPSAL.SALARY; -- 급여 저장
		TOTAL := TOTAL + V_NT_SALARY(V_NT_SALARY.COUNT); -- 누적
	END LOOP;
	IF V_NT_SALARY.COUNT > 0 THEN -- 급여데이터가 있다면 
		PL('평균 급여 : ' || ROUND(TOTAL/V_NT_SALARY.COUNT,2)); -- 평균을 소수점 두째자리 반올림
	ELSE 
		PL('해당 부서에 사원이 없음!');
	END IF;
END;


-- 3) 부서번호를 키로, 부서명을 값으로 하는 연관 배열을 구성하고 90번 부서의 부서명을 출력
DECLARE
	TYPE AA_DEPT IS TABLE OF DEPARTMENTS.DEPARTMENT_NAME%TYPE
	INDEX BY PLS_INTEGER; -- 인덱스는 정수(PLS_INTEGER) 또는 문자열
	V_AA_DEPT AA_DEPT;
BEGIN
	FOR DEPT IN (SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM DEPARTMENTS) 
	LOOP
		V_AA_DEPT(DEPT.DEPARTMENT_ID) := DEPT.DEPARTMENT_NAME;
	END LOOP;
	PL(V_AA_DEPT(90));
END;


-- 4) 사원ID가 102 이하인 사원 3명의 사원ID와 풀네임을 
--     RECORD와 중첩테이블에 저장하고 사원ID와 풀네임을 출력
DECLARE
	TYPE REC_EMP IS RECORD (
		EMPID EMPLOYEES.EMPLOYEE_ID%TYPE,
		FULLNAME VARCHAR2(46)
	);
	TYPE NT_EMP IS TABLE OF REC_EMP;
	V_NT_EMP NT_EMP := NT_EMP();
BEGIN
	FOR EMP IN (
		-- TOP-N QUERY (상위에서 몇 행 조회)
		SELECT * FROM (
			SELECT ROWNUM RN, EMPLOYEE_ID, FIRST_NAME||' '||LAST_NAME AS FULLNAME
			FROM EMPLOYEES WHERE EMPLOYEE_ID <= 102
		)
		WHERE RN <= 3
	)
	LOOP
		V_NT_EMP.EXTEND;
		V_NT_EMP(V_NT_EMP.COUNT).EMPID := EMP.EMPLOYEE_ID;
		V_NT_EMP(V_NT_EMP.COUNT).FULLNAME  := EMP.FULLNAME;
		PL(V_NT_EMP(V_NT_EMP.COUNT).EMPID);
		PL(V_NT_EMP(V_NT_EMP.COUNT).FULLNAME);
	END LOOP;
END;


-- 5) 중첩 RECORD를 사용하여 100번 직원의 풀네임과 부서아이디, 부서명을 출력

-- 6) JOBS테이블에서 JOB_ID를 키로, JOB_TITLE을 값으로 하는 연관배열을 생성하고
--     JOB_ID가 'SA_REP'인 직무의 직무명을 출력

-- 7) 부서별 사원수를 연관배열을 사용해 저장한 후 90번 부서의 사원수를 출력