-- TRIGGER 
-- DBMS에 이벤트 발생시 
-- 보안, 로깅, 백업 작업에 많이 활용

-- 트리거를 활용한 백업

-- 원본테이블
CREATE TABLE ORG_TABLE (
	OTNO NUMBER PRIMARY KEY,
	OTCONTENT NVARCHAR2(2000) NOT NULL 
);

-- 백업테이블 (원본테이블의 구조만 복사)
CREATE TABLE BK_TABLE
AS
SELECT * FROM ORG_TABLE
WHERE 1 = -1; -- 무조건 FALSE인 조건

-- 백업 트리거
CREATE OR REPLACE TRIGGER BK_TRIGGER
AFTER -- 트리거링 시점
INSERT ON ORG_TABLE -- 트리거링 원인 : ORG_TABLE에 INSERT가 일어나면 
FOR EACH ROW -- INSERT된 각 행에 대해서
BEGIN
	-- BK_TABLE에 새로 들어온 OTNO와 OTCONTENT를 INSERT함
	INSERT INTO BK_TABLE VALUES (:NEW.OTNO, :NEW.OTCONTENT);
END;

SELECT * FROM ORG_TABLE;
SELECT * FROM BK_TABLE;

INSERT INTO ORG_TABLE VALUES(1, '컨텐츠1');
INSERT INTO ORG_TABLE VALUES(2, '컨텐츠2');
INSERT INTO ORG_TABLE VALUES(3, '컨텐츠3');

SELECT * FROM ORG_TABLE;
SELECT * FROM BK_TABLE;

-- 트리거를 활용한 로깅
CREATE TABLE LOG_TABLE(
	LOG_NO NUMBER PRIMARY KEY, -- 로그 일련번호
	TBL_NAME VARCHAR2(100) NOT NULL, -- 테이블명
	DML  VARCHAR2(10), -- 수행 작업(DML)
	CONTENT NVARCHAR2(200), --작업상세
	LOG_DATE DATE -- 로그 일시
);

CREATE SEQUENCE SEQ_LOG;

-- 로깅 트리거
CREATE OR REPLACE TRIGGER LOG_TRIGGER -- 3.트리거 실행
AFTER --2.다음에
INSERT OR UPDATE OR DELETE ON ORG_TABLE --1. ORG_TABLE에 이러한 행위가 일어난
FOR EACH ROW
BEGIN
	IF INSERTING THEN
		INSERT INTO LOG_TABLE
		VALUES (SEQ_LOG.NEXTVAL, 'ORG_TABLE', 'INSERT', :NEW.OTCONTENT, SYSDATE);
	ELSIF UPDATING THEN
		INSERT INTO LOG_TABLE
		VALUES (SEQ_LOG.NEXTVAL, 'ORG_TABLE', 'UPDATE', 
			:OLD.OTCONTENT||' > '||:NEW.OTCONTENT, SYSDATE);
	ELSIF DELETING THEN
		INSERT INTO LOG_TABLE
		VALUES (SEQ_LOG.NEXTVAL, 'ORG_TABLE', 'DELETE', :OLD.OTNO, SYSDATE);
	END IF;
END;

-- ORG_TABLE에 INSERT
INSERT INTO ORG_TABLE VALUES (4, '컨텐츠4');
COMMIT;

SELECT * FROM ORG_TABLE;
SELECT * FROM BK_TABLE;
SELECT * FROM LOG_TABLE;

-- ORG_TABLE에 UPDATE
UPDATE ORG_TABLE SET OTCONTENT='수정컨텐츠4' WHERE OTNO=4;
COMMIT;

SELECT * FROM ORG_TABLE;
SELECT * FROM BK_TABLE;
SELECT * FROM LOG_TABLE;

-- ORG_TABLE에 DELETE
DELETE ORG_TABLE WHERE OTNO=4;
COMMIT;

SELECT * FROM ORG_TABLE;
SELECT * FROM BK_TABLE;
SELECT * FROM LOG_TABLE;

-- TRIGGER를 활용한 보안
CREATE OR REPLACE TRIGGER SECURE_TRIGGER
BEFORE
INSERT OR UPDATE OR DELETE ON ORG_TABLE
FOR EACH ROW
BEGIN
	IF INSERTING THEN
		RAISE_APPLICATION_ERROR(-20777, 'ORG_TABLE 입력 금지!');
	ELSIF UPDATING THEN
		RAISE_APPLICATION_ERROR(-20778, 'ORG_TABLE 수정 금지!');
	ELSIF DELETING THEN
		RAISE_APPLICATION_ERROR(-20779, 'ORG_TABLE 삭제 금지!');
	END IF;
END;

INSERT INTO ORG_TABLE VALUES (5, '콘텐츠5');
COMMIT;
SELECT * FROM ORG_TABLE;
SELECT * FROM BK_TABLE;
SELECT * FROM LOG_TABLE;

UPDATE ORG_TABLE SET OTCONTENT='수정컨텐츠1' WHERE OTNO=1;
COMMIT;
SELECT * FROM ORG_TABLE;
SELECT * FROM BK_TABLE;
SELECT * FROM LOG_TABLE;


DELETE ORG_TABLE WHERE OTNO=1;
COMMIT;
SELECT * FROM ORG_TABLE;
SELECT * FROM BK_TABLE;
SELECT * FROM LOG_TABLE;

-- 트리거 개별 활성화 / 비활성화
-- 트리거는 생성하면 자동으로 활성화 상태
ALTER TRIGGER LOG_TRIGGER DISABLE; -- 비활성화
ALTER TRIGGER LOG_TRIGGER ENABLE; -- 활성화

-- 테이블과 관련된 모든 트리거 활성화/비활성화
ALTER TABLE ORG_TABLE DISABLE ALL TRIGGERS; -- ORG_TABLE의 모든 트리거가 비활성화
ALTER TABLE ORG_TABLE ENABLE ALL TRIGGERS; -- ORG_TABLE의 모든 트리거가 활성화

-- 사용자 소유의 트리거 조회 데이터 사전
SELECT * FROM USER_TRIGGERS;
