-- 9.TRIGGER-CKY-실습.sql

CREATE TABLE EMP (
   EMP_ID NUMBER PRIMARY KEY,
   EMP_NAME NVARCHAR2(200) NOT NULL,
   EMP_SALARY NUMBER,
   EMP_COMM_PCT NUMBER
);

CREATE SEQUENCE SEQ_EMP;

INSERT INTO EMP VALUES (SEQ_EMP.NEXTVAL, '홍길동', 10000, 0.25);
INSERT INTO EMP VALUES (SEQ_EMP.NEXTVAL, '강감찬', 8000, 0.15);
INSERT INTO EMP VALUES (SEQ_EMP.NEXTVAL, '이순신', 6000, 0.05);
COMMIT;

SELECT * FROM EMP;

-- 1) 급여 삭감 방지 트리거 TRG_UPDATE_SALARY 생성 후 작동 확인
CREATE OR REPLACE TRIGGER TRG_UPDATE_SALARY
BEFORE
UPDATE ON EMP
FOR EACH ROW
BEGIN
	IF :OLD.EMP_SALARY > :NEW.EMP_SALARY
		THEN RAISE_APPLICATION_ERROR(-20771, '급여 삭감 안됨');
	END IF;
END;

-- ORG_TABLE에 INSERT
INSERT INTO EMP VALUES (4, '유관순', 20000, 0.30);
COMMIT;
SELECT * FROM EMP;

-- ORG_TABLE에 UPDATE
UPDATE EMP SET EMP_SALARY=30000 WHERE EMP_ID=4;
COMMIT;
SELECT * FROM EMP;

-- 2) 직원데이터 추가 및 삭제 로그 트리거 TRG_EMP 생성 후 작동 확인
CREATE TABLE LOG_EMP (
   EMP_ID NUMBER,
   EMP_NAME NVARCHAR2(200),
   DML NVARCHAR2(20),
   WORK_ID NUMBER,
   LOG_DATE DATE
);
CREATE SEQUENCE SEQ_LOG_EMP;

-- 로깅 트리거
CREATE OR REPLACE TRIGGER TRG_EMP -- 3.트리거 실행
AFTER --2.다음에
INSERT OR DELETE ON EMP --1. ORG_TABLE에 이러한 행위가 일어난
FOR EACH ROW
BEGIN
	IF INSERTING THEN
		INSERT INTO LOG_EMP
		VALUES (SEQ_LOG_EMP.NEXTVAL, :NEW.EMP_NAME,  'INSERT', :NEW.EMP_ID, SYSDATE);
	ELSIF DELETING THEN
		INSERT INTO LOG_EMP
		VALUES (SEQ_LOG_EMP.NEXTVAL, :NEW.EMP_NAME,  'DELETE', :NEW.EMP_ID, SYSDATE);
	END IF;
END;

-- ORG_TABLE에 INSERT
INSERT INTO EMP VALUES (SEQ_EMP.NEXTVAL, '김모모', 10000, 0.25);
COMMIT;
SELECT * FROM LOG_EMP;

-- ORG_TABLE에 DELETE
DELETE EMP WHERE OTNO=4;
COMMIT;
SELECT * FROM LOG_EMP;

-- 3) 신규 직원 추가시 기본 커미션(0.05) 부여 트리거 TRG_COMM_PCT 생성 후 작동 확인

-- 4) 급여 변경 이력관리 트리거 TRG_HISTORY_SALARY 생성 후 작동 확인
--     WORK:변경전급여와 변경후급여 내역
CREATE TABLE LOG_HISTORY_SALARY (
   EMP_ID NUMBER,
   EMP_NAME NVARCHAR2(200),
   WORK NVARCHAR2(2000),
   LOG_DATE DATE
);

-- 5) EMP테이블의 백업 트리거 TRG_BK_EMP : 항상 EMP테이블과 동일한 데이터 유지하도록
CREATE TABLE BK_EMP
AS
SELECT * FROM EMP;




































