CREATE TABLE FILE_STORAGE (
	FSID NUMBER PRIMARY KEY,
	FSFNAME NVARCHAR2(500) NOT NULL,
	FSTYPE CHAR(4) CHECK (FSTYPE IN  ('BLOB', 'CLOB')),
	FSDATA BLOB  -- BLOB TYPE
);

CREATE SEQUENCE SEQ_FILE_STORAGE;

SELECT * FROM FILE_STORAGE;

CREATE TABLE TEXT_STORAGE (
	TSID NUMBER PRIMARY KEY,
	TSFNAME NVARCHAR2(500) NOT NULL,
	TSFTYPE CHAR(4) CHECK (TSFTYPE IN  ('BLOB', 'CLOB')),
	TSDATA CLOB  -- CLOB TYPE
);

CREATE SEQUENCE SEQ_TEXT_STORAGE;

SELECT * FROM TEXT_STORAGE;