CREATE TABLE BOARD (
	BNO NUMBER PRIMARY KEY, -- 번호
	BDATE TIMESTAMP,  -- 작성일시
	BWRITER NVARCHAR2(200) NOT NULL, -- 작성자
	BTITLE NVARCHAR2(2000), -- 제목
	BCONTENT NVARCHAR2(2000), -- 내용
 	BFNAME NVARCHAR2(200), -- 첨부파일명
	BVIEWS NUMBER -- 조회수
);

CREATE SEQUENCE SEQ_BOARD;