CREATE TABLE TODO (
	TDNO NUMBER PRIMARY KEY, -- 순번
	TDDATE TIMESTAMP, -- 작성일시
	TDWRITER NVARCHAR2(200) NOT NULL, -- 작성자
	TDCONTENT NVARCHAR2(2000), -- 내용
	TDYN CHAR(1) CHECK (TDYN IN ('Y', 'N')) -- 완료여부
);

CREATE SEQUENCE SEQ_TODO;

SELECT * FROM TODO;