CREATE TABLE PERSON (
	PID NUMBER PRIMARY KEY,
	PNAME NVARCHAR2(200) NOT NULL,
	PAGE NUMBER CHECK (PAGE > 0)
);

CREATE SEQUENCE SEQ_PERSON;

SELECT * FROM PERSON;

-- 아이디에 해당하는 이름 변경
--P_PNAME으로 이름을 받아오고, 변경된 이름을 다시 P_PNAME으로 보내줌
CREATE OR REPLACE PROCEDURE CHANGE_PNAME (
	P_PID IN NUMBER,
	--1. 파라미터로 변경할 이름 받아오기
	P_PNAME IN OUT NVARCHAR2 -- 자릿수 빼기
)
IS
BEGIN
	UPDATE PERSON SET PNAME=P_PNAME WHERE PID=P_PID;
	COMMIT;
	--2. 변경한 이름을 다시 P_PNAME으로 보내기
	SELECT PNAME INTO P_PNAME FROM PERSON WHERE PID=P_PID; -- 변경한 이름을 P_PNAME에 넣어서 다시 OUT으로 보냄
END;

-- PID에 해당하는 PNAME을 반환하는 함수
CREATE OR REPLACE FUNCTION GET_PNAME(P_PID IN NUMBER)
RETURN NVARCHAR2
IS
	V_PNAME PERSON.PNAME%TYPE;
BEGIN
	SELECT PNAME INTO V_PNAME
	FROM PERSON
	WHERE PID=P_PID;
	RETURN V_PNAME;
	EXCEPTION
		WHEN NO_DATA_FOUND THEN
		RETURN 'PID에 해당하는 데이터가 없음!';
END;
