CREATE TABLE STUDENT (
	SID NUMBER PRIMARY KEY,
	SNAME NVARCHAR2(200) NOT NULL,
	SPHONE CHAR(13),
	SEMAIL NVARCHAR2(200)
);

CREATE SEQUENCE SEQ_STUDENT;

CREATE TABLE LECTURE(
	LID NUMBER PRIMARY KEY,
	LNAME NVARCHAR2(200) NOT NULL
);

CREATE SEQUENCE SEQ_LECTURE;

CREATE TABLE SCORE(
	SID NUMBER,
	LID NUMBER,
	FOREIGN KEY (SID) REFERENCES STUDENT (SID),
	FOREIGN KEY (LID) REFERENCES LECTURE (LID)
);

INSERT INTO STUDENT 
VALUES(SEQ_STUDENT.NEXTVAL, '홍길동','010-0000-0000', 'HONG@HONG.COM');

INSERT INTO STUDENT 
VALUES(SEQ_STUDENT.NEXTVAL, '강감찬', '010-0000-0000', 'KANG@KANG.COM');

INSERT INTO STUDENT 
VALUES(SEQ_STUDENT.NEXTVAL, '이순신', '010-0000-0000', 'LEE@LEE.COM');
COMMIT;
SELECT * FROM STUDENT;

INSERT INTO LECTURE
VALUES(SEQ_LECTURE.NEXTVAL, '철학의 이해');

INSERT INTO LECTURE
VALUES(SEQ_LECTURE.NEXTVAL, '영화의 이해');

INSERT INTO LECTURE
VALUES(SEQ_LECTURE.NEXTVAL, '요리의 이해');
COMMIT;
SELECT * FROM LECTURE;

INSERT INTO SCORE VALUES(1,1,90);
INSERT INTO SCORE VALUES(1,2,50);
INSERT INTO SCORE VALUES(1,3,30);
INSERT INTO SCORE VALUES(2,1,100);
INSERT INTO SCORE VALUES(2,2,60);
INSERT INTO SCORE VALUES(2,3,90);
INSERT INTO SCORE VALUES(3,1,85);
INSERT INTO SCORE VALUES(3,2,20);
INSERT INTO SCORE VALUES(3,3,100);
COMMIT;
SELECT * FROM SCORE;

-- GRANT CREATE VIEW TO SCORE;***********
CREATE OR REPLACE VIEW VW_ALL_INFO
AS 
SELECT S.SID, S.SNAME, S.SEMAIL, 
S.SPHONE, SC.SSCORE, L.LID, L.LNAME
FROM SCORE SC
JOIN STUDENT S ON SC.SID = S.SID
JOIN LECTURE L ON SC.LID = L.LID;

-- 뷰를 통해서 데이터 조회
SELECT * FROM VW_ALL_INFO;