CREATE TABLE STUDENT (
	STNO NUMBER PRIMARY KEY,
	STNAME VARCHAR2(20) NOT NULL,
	STEMAIL VARCHAR2(200),
	STPHONE VARCHAR2(20)
);

CREATE SEQUENCE SEQ_STUDENT;

SELECT * FROM STUDENT;

-- 한 행의 데이터를 입력하는 프로시저 PROC_INSERT_STUDENT
CREATE OR REPLACE PROCEDURE PROC_INSERT_STUDENT (
	P_STNAME IN STUDENT.STNAME%TYPE,
	P_STEMAIL IN STUDENT.STEMAIL%TYPE,
	P_STPHONE IN STUDENT.STPHONE%TYPE
)
IS
BEGIN
	INSERT INTO STUDENT VALUES(
		SEQ_STUDENT.NEXTVAL, 
		P_STNAME,
		P_STEMAIL,
		P_STPHONE
	);
	COMMIT;
END;

-- STNO를 입력하면 이름을 반환하는 함수
CREATE  OR REPLACE FUNCTION FUNC_GET_STNAME (P_STNO IN STUDENT.STNO%TYPE)
RETURN STUDENT.STNAME%TYPE
IS
	V_STNAME STUDENT.STNAME%TYPE;
BEGIN
	-- STNO에 해당하는 이름을 가져와서 변수에 저장하기
	SELECT STNAME INTO V_STNAME
	FROM STUDENT
	WHERE STNO=P_STNO;
	RETURN V_STNAME;
	EXCEPTION
		WHEN NO_DATA_FOUND THEN
		RETURN 'PID에 해당하는 데이터가 없음!';
END;

