CREATE TABLE STUDENT (
	SID NUMBER PRIMARY KEY,
	SNAME NVARCHAR2(200) NOT NULL,
	SMAJOR NVARCHAR2(200),
	SPHONE CHAR(13),
	SEMAIL NVARCHAR2(200)
);

CREATE SEQUENCE SEQ_STUDENT;

CREATE TABLE LECTURE(
	LID NUMBER PRIMARY KEY,
	LNAME NVARCHAR2(200) NOT NULL,
	LTIMETABLE NVARCHAR2(2000)
);

CREATE SEQUENCE SEQ_LECTURE;

CREATE TABLE PROFESSOR(
	PID NUMBER PRIMARY KEY,
	PNAME NVARCHAR2(200) NOT NULL,
	PMAJOR NVARCHAR2(200),
	PPHONE CHAR(13),
	PEMAIL NVARCHAR2(200)
);

CREATE SEQUENCE SEQ_PROFESSOR;

CREATE TABLE STUDENTLECTURE(
	SID NUMBER,
	LID NUMBER,
	FOREIGN KEY (SID) REFERENCES STUDENT (SID),
	FOREIGN KEY (LID) REFERENCES LECTURE (LID)
);

CREATE TABLE PROFESSORLECTURE(
	PID NUMBER,
	LID NUMBER,
	FOREIGN KEY (PID) REFERENCES PROFESSOR (PID),
	FOREIGN KEY (LID) REFERENCES LECTURE (LID)
);

INSERT INTO STUDENT 
VALUES(SEQ_STUDENT.NEXTVAL, '홍길동', '철학', '010-0000-0000', 'HONG@HONG.COM');

INSERT INTO STUDENT 
VALUES(SEQ_STUDENT.NEXTVAL, '강감찬', '수학', '010-0000-0000', 'KANG@KANG.COM');

INSERT INTO STUDENT 
VALUES(SEQ_STUDENT.NEXTVAL, '이순신', '과학', '010-0000-0000', 'LEE@LEE.COM');
COMMIT;
SELECT * FROM STUDENT;

INSERT INTO LECTURE
VALUES(SEQ_LECTURE.NEXTVAL, '철학의 이해', '매주 수요일,금요일 14-16시');

INSERT INTO LECTURE
VALUES(SEQ_LECTURE.NEXTVAL, '영화의 이해', '매주 화요일,목요일 14-16시');
COMMIT;
SELECT * FROM LECTURE;

INSERT INTO PROFESSOR
VALUES(SEQ_PROFESSOR.NEXTVAL, '아인슈타인', '물리학', '010-0000-0000', 'EIN@EIN.COM');

INSERT INTO PROFESSOR
VALUES(SEQ_PROFESSOR.NEXTVAL, '테슬라', '전기공학', '010-0000-0000', 'TESLA@TESLA.COM');
COMMIT;
SELECT * FROM PROFESSOR;

INSERT INTO STUDENTLECTURE VALUES(1,1);
INSERT INTO STUDENTLECTURE VALUES(1,2);
INSERT INTO STUDENTLECTURE VALUES(2,1);
INSERT INTO STUDENTLECTURE VALUES(2,2);
INSERT INTO STUDENTLECTURE VALUES(3,1);
COMMIT;
SELECT * FROM STUDENTLECTURE;

TRUNCATE TABLE PROFESSORLECTURE;
INSERT INTO PROFESSORLECTURE VALUES(1,1);
INSERT INTO PROFESSORLECTURE VALUES(1,2);
INSERT INTO PROFESSORLECTURE VALUES(2,1);
INSERT INTO PROFESSORLECTURE VALUES(2,2);
COMMIT;
SELECT * FROM PROFESSORLECTURE;
